name: ransomwatch

on:
  schedule:
    - cron: '*/50 * * * *'
  workflow_dispatch:

# to consider: the use of action jobs to breakout each task
# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

jobs:
  torsocks-job:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    services:
      torproxy:
        image: ghcr.io/xfivesao/ransomwatch/torproxy:latest
        ports:
        - 9050:9050
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: run scraper
        run: |
          python3 ransomwatch.py scrape
      - name: run parser
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python3 ransomwatch.py parse
      - name: generate markdown & graphs for docsify
        run: |
          python3 ransomwatch.py markdown
      - name: save changes
        run: |
          git config --global user.email "devgru@tutanota.com"
          git config --global user.name "xfivesao"
          git commit --all --message "Updated by RW Tracker LV4" || echo "no changes to commit"
          git push
